### ISSUE TITLE
Update `_getDisplayPos`?

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/readline2#3]
Noticed that the `_getDisplayPos` function were different from Node.js master and found this commit: https://github.com/nodejs/io.js/commit/93c3674ff7115fb2a3dbb5b4ffd22f4d5ed9a472

That should probably be implemented here too, right?

**Comment by SBoudrias** [comment]
Oh yes, probably. This could also greatly simplified the automatic new line handling done in Inquirer.

I'll check into it.
